"""create preprocess_call_log table

Revision ID: a8642b6b71af
Revises: b4efebf249b0
Create Date: 2026-07-30 14:55:02.746555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8642b6b71af'
down_revision: Union[str, Sequence[str], None] = 'b4efebf249b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preprocess_call_log',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_country_code', sa.String(length=16), nullable=True),
    sa.Column('client_number', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.String(length=32), nullable=True),
    sa.Column('call_date', sa.String(length=16), nullable=True),
    sa.Column('call_time', sa.String(length=16), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('call_recording_url', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.String(length=64), nullable=True),
    sa.Column('modified_at', sa.String(length=64), nullable=True),
    sa.Column('emp_name', sa.String(length=255), nullable=True),
    sa.Column('emp_code', sa.String(length=64), nullable=True),
    sa.Column('emp_number', sa.String(length=32), nullable=True),
    sa.Column('emp_country_code', sa.String(length=16), nullable=True),
    sa.Column('emp_tags', sa.String(length=255), nullable=True),
    sa.Column('crm_status', sa.String(length=64), nullable=True),
    sa.Column('reminder_date', sa.String(length=16), nullable=True),
    sa.Column('reminder_time', sa.String(length=16), nullable=True),
    sa.Column('lead_id', sa.String(length=128), nullable=True),
    sa.Column('google_drive_link', sa.Text(), nullable=True),
    sa.Column('ai_transcript', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('sub_reason', sa.Text(), nullable=True),
    sa.Column('commitment', sa.String(length=128), nullable=True),
    sa.Column('intimation', sa.String(length=128), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('valid_discussion', sa.String(length=32), nullable=True),
    sa.Column('ai_analysis_confidence', sa.String(length=32), nullable=True),
    sa.Column('ai_analysis_explanation', sa.Text(), nullable=True),
    sa.Column('analysis_status', sa.String(length=32), nullable=True),
    sa.Column('analysis_updated_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preprocess_call_log')
    # ### end Alembic commands ###
